version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      day: tuesday
      time: '14:00'
    open-pull-requests-limit: 20
    labels:
      - dependencies
