trigger:
- main

pr:
- main

pool:
  vmImage: 'macos-latest'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- task: UseNode@1
  displayName: 'Use Node 10.x'
  inputs:
    version: 10.x

- template: '../steps/run-tests.yml'
  parameters:
    envName: 'Mac'
